 glove_dir : '../../../animesh/glove/'
 data_file : 'WikiQA-train.tsv'
 embedding_size : 50
 vocab_length : 400000
 learning_rate : 0.001
 dropout : 0.5
 vocab_file : 'voc.txt'
 embedding_file: 'emb.txt'
 not_exist_index : 400000
 batch_size : 16
 n_hidden : 128
 margin : 0.2
 num_epochs : 20
 max_sequence_length : 50
 dropout : 0.6